@startuml
用户 --> 小程序首页:搜索简计划
小程序首页 --> 列表添加页面:点击右下角“+”，\n选择添加清单
小程序首页-->任务添加页面:在首页找到需要\n添加任务的清单，\n点击它右上方的“···”，\n选择添加任务
小程序首页-->任务修改页面:在首页左滑需要\n修改的任务，点击修改
@enduml
@startuml
:user: --> (任务清单)
(任务清单)..>(清单删除):include
(任务清单)..>(清单修改):include
(任务清单)..>(清单创建):include
(清单创建)-->(任务)
(任务)..>(任务修改)
(任务)..>(任务提醒)
(任务)..>(任务创建)
(任务)..>(任务分配)
:user2:<--(任务分配)
@enduml
@startuml
class 用户
用户 ”1“ --o ”many“ 任务清单
任务清单 ”1“ --o ”many“ 任务
任务 ”1“ --* ”many“ 任务步骤
用户 ”many“ --o "many"  任务
@enduml
@startuml
database "Mysql" as mysql
[权限模块]-登录
[权限模块]-left--注册
[权限模块]..>用户查询:调用
[系统模块]-用户查询
[系统模块]-->mysql:查询数据库
[任务管理模块]-登录2
[任务管理模块]-left-注册2
[任务管理模块]..>登录:调用
[任务管理模块]..>注册:调用
@enduml
@startuml
state choice1 <<choice>>
[*]-down-> 输入用户名
输入用户名 -down-> choice1 :判断用户名是否存在
choice1-left->输入用户名: 已经存在
choice1-down->密码加密
密码加密->注册
@enduml
@startuml
object 任务清单
object 任务步骤
map 任务{
清单 *->任务清单
步骤 *->任务步骤
}
@enduml
@startuml

@enduml